name: pieklo_nurki
description: "Pieklo nurki do pieklo podow"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.5
  webview_flutter: ^4.7.0
  cupertino_icons: ^1.0.2
  expandable_menu: ^0.0.5
  flutter_svg_provider: ^1.0.7
  scrollable: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/stratagems/Bridge/
    - assets/stratagems/Engineering_Bay/
    - assets/stratagems/General_Stratagems/
    - assets/stratagems/Hangar/
    - assets/stratagems/Orbital_Cannons/
    - assets/stratagems/Patriotic_Administration_Center/
    - assets/stratagems/Robotics_Workshop/
    - assets/stratagemsCombos.txt
    - assets/images/
    - assets/intro_cropped.mp4
    - assets/fonts/Quicksand/
    - assets/fonts/Quicksand/static/
    - assets/fonts/Chakra_Petch/

  fonts:
    - family: Quicksand
      fonts:
#        - asset: assets/fonts/Quicksand/Quicksand-VariableFont_wght.ttf
        - asset: assets/fonts/Quicksand/static/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand/static/Quicksand-Bold.ttf
          weight: 700

    - family: ChakraPetch
      fonts:
        - asset: assets/fonts/Chakra_Petch/ChakraPetch-Light.ttf
          weight: 200
        - asset: assets/fonts/Chakra_Petch/ChakraPetch-Regular.ttf
          weight: 400
        - asset: assets/fonts/Chakra_Petch/ChakraPetch-Medium.ttf
          weight: 500
        - asset: assets/fonts/Chakra_Petch/ChakraPetch-Bold.ttf
          weight: 700

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
