name: pieklo_nurki
description: "Pieklo nurki do pieklo podow"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.5
  webview_flutter: ^4.7.0
  cupertino_icons: ^1.0.2
  expandable_menu: ^0.0.5
  flutter_svg_provider: ^1.0.7
  scrollable: ^1.0.5
  marquee_text: ^2.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/stratagems.json
    - assets/stratagems/Bridge/
    - assets/stratagems/Engineering_Bay/
    - assets/stratagems/General_Stratagems/
    - assets/stratagems/Hangar/
    - assets/stratagems/Orbital_Cannons/
    - assets/stratagems/Patriotic_Administration_Center/
    - assets/stratagems/Robotics_Workshop/
    - assets/images/
    - assets/intro_cropped.mp4
    - assets/fonts/Chakra_Petch/

  fonts:
    - family: ChakraPetch
      fonts:
        - asset: assets/fonts/Chakra_Petch/ChakraPetch-Light.ttf
          weight: 200
        - asset: assets/fonts/Chakra_Petch/ChakraPetch-Regular.ttf
          weight: 400
        - asset: assets/fonts/Chakra_Petch/ChakraPetch-Medium.ttf
          weight: 500
        - asset: assets/fonts/Chakra_Petch/ChakraPetch-Bold.ttf
          weight: 700
